version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - RAPID7_API_KEY=your_actual_api_key_here
    restart: unless-stopped 